
;; Org-mode keybindings
(evil-leader/set-key "oo" 'open-org-dir)
(evil-leader/set-key "oa" 'my-org-archive-done-tasks)
(evil-leader/set-key "og" 'gtd)
(evil-leader/set-key "oj" 'journal)
(evil-leader/set-key "ot" 'org-capture)
(evil-leader/set-key "on" 'notes)
(evil-leader/set-key "oG" 'groceries)
(evil-leader/set-key "oi" 'gtd-inbox)
(evil-leader/set-key "oI" 'gtd-inbox-txt)
(evil-leader/set-key "oU" 'org-mobile-push)
(evil-leader/set-key "oD" 'org-mobile-pull)
(evil-leader/set-key "oek" 'edit-personal-keybindings)
(evil-leader/set-key "oef" 'edit-personal-funcs)
(evil-leader/set-key "of" 'ff-find-other-file)
(evil-leader/set-key "*y" 'clipboard-kill-region)
(evil-leader/set-key "*p" 'clipboard-yank)

(defun custom-org-agenda-mode-defaults ()
  (org-defkey org-agenda-mode-map "W" 'oh/agenda-remove-restriction)
  (org-defkey org-agenda-mode-map "N" 'oh/agenda-restrict-to-subtree)
  (org-defkey org-agenda-mode-map "P" 'oh/agenda-restrict-to-project)
  (org-defkey org-agenda-mode-map "q" 'bury-buffer)
  (org-defkey org-agenda-mode-map "I" 'org-clock-in)
  (org-defkey org-agenda-mode-map "O" 'org-clock-out)
  )
