;; Org-mode keybindings
(defun open-org-dir ()
  "Opens the org dir"
  (interactive)
  (find-file "~/org/")
  )
(defun gtd-inbox ()
  "Open the gtd inbox"
  (interactive)
  (find-file "~/org/inbox.org")
  )
(defun gtd-inbox-txt ()
  "Open the gtd inbox"
  (interactive)
  (find-file "~/org/inbox.org.txt")
  )
(defun work-list ()
  "Open GTD directory"
  (interactive)
  (find-file "~/org/gtd/work.org")
  )
(defun home-list ()
  "Open GTD directory"
  (interactive)
  (find-file "~/org/gtd/private.org")
  )
(defun journal ()
  "Open Journal"
  (interactive)
  (find-file "~/org/journal.org")
  )
(defun notes ()
  "Switch to my work dir."
  (interactive)
  (find-file "~/org/notes/")
  )
(defun groceries ()
  "Edit grocery list"
  (interactive)
  (find-file "~/org/groceries.org")
  )

(defun my-org-archive-done-tasks ()
  (interactive)
  (org-map-entries 'org-archive-subtree "/DONE" 'file)
  )

(setq org-indirect-buffer-display 'current-window)
(defun bh/verify-refile-target ()
  "Exclude todo keywords with a done state from refile targets"
  (not (member (nth 2 (org-heading-components)) org-done-keywords)))
(setq org-refile-target-verify-function 'bh/verify-refile-target)

(evil-leader/set-key "oo" 'open-org-dir)
(evil-leader/set-key "oa" 'org-agenda)
(evil-leader/set-key "oA" 'my-org-archive-done-tasks)
(evil-leader/set-key "og" 'gtd)
(evil-leader/set-key "oJ" 'journal)
(evil-leader/set-key "ot" 'org-capture)
(evil-leader/set-key "on" 'notes)
(evil-leader/set-key "oG" 'groceries)
(evil-leader/set-key "oi" 'gtd-inbox)
(evil-leader/set-key "oI" 'gtd-inbox-txt)
(evil-leader/set-key "oU" 'org-mobile-push)
(evil-leader/set-key "oD" 'org-mobile-pull)
(evil-leader/set-key "oek" 'edit-personal-keybindings)
(evil-leader/set-key "oef" 'edit-personal-funcs)
(evil-leader/set-key "of" 'ff-find-other-file)
(evil-leader/set-key "*y" 'clipboard-kill-region)
(evil-leader/set-key "*p" 'clipboard-yank)
